
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int lcb = 94;
  public static final int delay = 55;
  public static final int declare = 53;
  public static final int return = 5;
  public static final int mod = 66;
  public static final int reverse = 9;
  public static final int else = 3;
  public static final int entry = 14;
  public static final int delta = 59;
  public static final int punto = 87;
  public static final int qm = 79;
  public static final int pragma = 38;
  public static final int accept = 13;
  public static final int null = 12;
  public static final int abstract = 10;
  public static final int for = 27;
  public static final int do = 65;
  public static final int generic = 33;
  public static final int procedure = 44;
  public static final int body = 40;
  public static final int exit = 21;
  public static final int dos = 89;
  public static final int vertical = 91;
  public static final int box = 78;
  public static final int pc = 90;
  public static final int begin = 36;
  public static final int case = 46;
  public static final int range = 54;
  public static final int is = 51;
  public static final int lsqb = 92;
  public static final int tagged = 32;
  public static final int rlb = 77;
  public static final int in = 47;
  public static final int or = 22;
  public static final int function = 30;
  public static final int op = 85;
  public static final int if = 43;
  public static final int separate = 19;
  public static final int id = 100;
  public static final int constant = 49;
  public static final int dataTypes = 70;
  public static final int doubdaps = 73;
  public static final int abs = 6;
  public static final int of = 18;
  public static final int end = 11;
  public static final int rem = 61;
  public static final int oprel = 88;
  public static final int arrow = 71;
  public static final int requeue = 67;
  public static final int exception = 17;
  public static final int rsqb = 93;
  public static final int type = 45;
  public static final int new = 4;
  public static final int ns = 80;
  public static final int noteq = 75;
  public static final int raise = 52;
  public static final int llb = 76;
  public static final int and = 26;
  public static final int until = 50;
  public static final int elsif = 7;
  public static final int access = 16;
  public static final int xor = 68;
  public static final int EOF = 0;
  public static final int at = 31;
  public static final int ap = 82;
  public static final int am = 81;
  public static final int abort = 2;
  public static final int limited = 56;
  public static final int private = 41;
  public static final int subtype = 25;
  public static final int loop = 60;
  public static final int array = 29;
  public static final int error = 1;
  public static final int get = 98;
  public static final int exp = 96;
  public static final int aliased = 20;
  public static final int task = 35;
  public static final int digits = 63;
  public static final int packageA = 34;
  public static final int then = 42;
  public static final int goto = 37;
  public static final int renames = 64;
  public static final int record = 57;
  public static final int rcb = 95;
  public static final int all = 23;
  public static final int assign = 74;
  public static final int when = 58;
  public static final int put = 99;
  public static final int lp = 83;
  public static final int select = 15;
  public static final int others = 24;
  public static final int terminate = 39;
  public static final int coma = 86;
  public static final int rp = 84;
  public static final int out = 28;
  public static final int not = 8;
  public static final int while = 62;
  public static final int doubd = 72;
  public static final int guinb = 97;
  public static final int num = 69;
  public static final int protected = 48;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "abort",
  "else",
  "new",
  "return",
  "abs",
  "elsif",
  "not",
  "reverse",
  "abstract",
  "end",
  "null",
  "accept",
  "entry",
  "select",
  "access",
  "exception",
  "of",
  "separate",
  "aliased",
  "exit",
  "or",
  "all",
  "others",
  "subtype",
  "and",
  "for",
  "out",
  "array",
  "function",
  "at",
  "tagged",
  "generic",
  "packageA",
  "task",
  "begin",
  "goto",
  "pragma",
  "terminate",
  "body",
  "private",
  "then",
  "if",
  "procedure",
  "type",
  "case",
  "in",
  "protected",
  "constant",
  "until",
  "is",
  "raise",
  "declare",
  "range",
  "delay",
  "limited",
  "record",
  "when",
  "delta",
  "loop",
  "rem",
  "while",
  "digits",
  "renames",
  "do",
  "mod",
  "requeue",
  "xor",
  "num",
  "dataTypes",
  "arrow",
  "doubd",
  "doubdaps",
  "assign",
  "noteq",
  "llb",
  "rlb",
  "box",
  "qm",
  "ns",
  "am",
  "ap",
  "lp",
  "rp",
  "op",
  "coma",
  "punto",
  "oprel",
  "dos",
  "pc",
  "vertical",
  "lsqb",
  "rsqb",
  "lcb",
  "rcb",
  "exp",
  "guinb",
  "get",
  "put",
  "id"
  };
}

