
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AT = 31;
  public static final int OPREL = 92;
  public static final int AP = 86;
  public static final int PACKAGEA = 34;
  public static final int LIMITED = 56;
  public static final int ARROW = 75;
  public static final int RSQB = 97;
  public static final int AM = 85;
  public static final int TYPE = 45;
  public static final int SUBTYPE = 74;
  public static final int ALIASED = 20;
  public static final int NOTEQ = 79;
  public static final int RAISE = 52;
  public static final int GET = 102;
  public static final int EXP = 100;
  public static final int RENAMES = 64;
  public static final int UNTIL = 50;
  public static final int ELSIF = 7;
  public static final int TERMINATE = 39;
  public static final int RCB = 99;
  public static final int ALL = 23;
  public static final int LP = 87;
  public static final int DECLARE = 53;
  public static final int ABORT = 2;
  public static final int PUT = 103;
  public static final int ACCESS = 16;
  public static final int LOOP = 60;
  public static final int RP = 88;
  public static final int PROTECTED = 48;
  public static final int OUT = 28;
  public static final int FALSE = 71;
  public static final int NOT = 8;
  public static final int TASK = 35;
  public static final int ARRAY = 29;
  public static final int THEN = 42;
  public static final int GOTO = 37;
  public static final int NUM = 72;
  public static final int RECORD = 57;
  public static final int REVERSE = 9;
  public static final int LCB = 98;
  public static final int MOD = 66;
  public static final int WHEN = 58;
  public static final int DOUBAPS = 77;
  public static final int GENERIC = 33;
  public static final int DIGITS = 63;
  public static final int SELECT = 15;
  public static final int COMA = 90;
  public static final int OTHERS = 24;
  public static final int ABSTRACT = 10;
  public static final int QM = 83;
  public static final int TRUE = 70;
  public static final int WHILE = 62;
  public static final int ASSIGN = 78;
  public static final int DOUBD = 76;
  public static final int GUINB = 101;
  public static final int DO = 65;
  public static final int FOR = 27;
  public static final int RETURN = 5;
  public static final int DELAY = 55;
  public static final int ELSE = 3;
  public static final int DOS = 93;
  public static final int PROCEDURE = 44;
  public static final int ENTRY = 14;
  public static final int DELTA = 59;
  public static final int PRAGMA = 38;
  public static final int NULL = 12;
  public static final int BOX = 82;
  public static final int EOF = 0;
  public static final int VERTICAL = 95;
  public static final int PUNTO = 91;
  public static final int COMMENT = 69;
  public static final int PC = 94;
  public static final int FUNCTION = 30;
  public static final int DATATYPES = 73;
  public static final int IS = 51;
  public static final int CONSTANT = 49;
  public static final int RLB = 81;
  public static final int BODY = 40;
  public static final int ACCEPT = 13;
  public static final int IN = 47;
  public static final int OR = 22;
  public static final int error = 1;
  public static final int EXIT = 21;
  public static final int OP = 89;
  public static final int IF = 43;
  public static final int ID = 104;
  public static final int OF = 18;
  public static final int ABS = 6;
  public static final int END = 11;
  public static final int REM = 61;
  public static final int REQUEUE = 67;
  public static final int SEPARATE = 19;
  public static final int BEGIN = 36;
  public static final int CASE = 46;
  public static final int LSQB = 96;
  public static final int EXCEPTION = 17;
  public static final int NEW = 4;
  public static final int SUBPROCEDURE = 25;
  public static final int TAGGED = 32;
  public static final int NS = 84;
  public static final int RANGE = 54;
  public static final int LLB = 80;
  public static final int AND = 26;
  public static final int PRIVATE = 41;
  public static final int XOR = 68;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ABORT",
  "ELSE",
  "NEW",
  "RETURN",
  "ABS",
  "ELSIF",
  "NOT",
  "REVERSE",
  "ABSTRACT",
  "END",
  "NULL",
  "ACCEPT",
  "ENTRY",
  "SELECT",
  "ACCESS",
  "EXCEPTION",
  "OF",
  "SEPARATE",
  "ALIASED",
  "EXIT",
  "OR",
  "ALL",
  "OTHERS",
  "SUBPROCEDURE",
  "AND",
  "FOR",
  "OUT",
  "ARRAY",
  "FUNCTION",
  "AT",
  "TAGGED",
  "GENERIC",
  "PACKAGEA",
  "TASK",
  "BEGIN",
  "GOTO",
  "PRAGMA",
  "TERMINATE",
  "BODY",
  "PRIVATE",
  "THEN",
  "IF",
  "PROCEDURE",
  "TYPE",
  "CASE",
  "IN",
  "PROTECTED",
  "CONSTANT",
  "UNTIL",
  "IS",
  "RAISE",
  "DECLARE",
  "RANGE",
  "DELAY",
  "LIMITED",
  "RECORD",
  "WHEN",
  "DELTA",
  "LOOP",
  "REM",
  "WHILE",
  "DIGITS",
  "RENAMES",
  "DO",
  "MOD",
  "REQUEUE",
  "XOR",
  "COMMENT",
  "TRUE",
  "FALSE",
  "NUM",
  "DATATYPES",
  "SUBTYPE",
  "ARROW",
  "DOUBD",
  "DOUBAPS",
  "ASSIGN",
  "NOTEQ",
  "LLB",
  "RLB",
  "BOX",
  "QM",
  "NS",
  "AM",
  "AP",
  "LP",
  "RP",
  "OP",
  "COMA",
  "PUNTO",
  "OPREL",
  "DOS",
  "PC",
  "VERTICAL",
  "LSQB",
  "RSQB",
  "LCB",
  "RCB",
  "EXP",
  "GUINB",
  "GET",
  "PUT",
  "ID"
  };
}

